CREATE USER inspect WITH PASSWORD 'inspect';
ALTER USER inspect CREATEDB;
ALTER DATABASE inspect_ai OWNER TO inspect;
GRANT ALL PRIVILEGES ON DATABASE inspect_ai TO inspect;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO inspect;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO inspect;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO inspect;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO inspect;
